import {
  CALENDAR_PATH,
  COMPONENT_PREVIEW_PATH,
  GROUP_SELECTION_PATH,
  PRIVATE_PATHS,
  PUBLIC_PATHS,
  ROOT_PATH,
  STUDENTS_PATH,
  TODAY_PATH,
  WELCOME_PATH,
} from "./navigation-paths";
import { KINDERGARTEN_GROUPS } from "./groups";

export {
  CALENDAR_PATH,
  COMPONENT_PREVIEW_PATH,
  GROUP_SELECTION_PATH,
  KINDERGARTEN_GROUPS,
  PRIVATE_PATHS,
  PUBLIC_PATHS,
  ROOT_PATH,
  STUDENTS_PATH,
  TODAY_PATH,
  WELCOME_PATH,
};
